### Listar todos os coletores
GET http://localhost:8085/api/coletores

### Criar um novo coletor
POST http://localhost:8085/api/coletores
Content-Type: application/json

{
  "nome": "Triciclo Elétrico Delta",
  "descricao": "Silencioso e ecológico, ideal para condomínios."
}