spring.application.name=demo

# Configuração do Banco de Dados H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do DataSource
spring.datasource.url=jdbc:h2:mem:ecorotadb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver

# Configuração do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

debug=true

server.port = 8085